### ISSUE TITLE
[DOCS] Add a license

### ISSUE THREAD

**Issue by AbbeyIT** [FOR-TIMI/weather-App#1]
Your project is very nice. It would be nice if you put a license on it. If you don't know why you need a license and what license to choose, you can refer to this [website](https://choosealicense.com/).

**Comment by FOR-TIMI** [comment]
> don't know why you need a license and what license to choose, you can refer to this

Hey, I'd do just that. Thanks :)

**Comment by FOR-TIMI** [comment]
Added License

**Comment by AbbeyIT** [comment]
Awesome!
